# https://www.appveyor.com/docs/appveyor-yml/

version: 1.1.0.{build}
branches:
  only:
    - master
skip_tags: true
image: Visual Studio 2017
platform:
  - Any CPU
configuration:
  - Release
build:
  parallel: true
  project: Irony-VS.sln
environment:
  EnableNuGetPackageRestore: true
before_build:
  nuget restore
after_build:
  - 7z a irony.zip -r %APPVEYOR_BUILD_FOLDER%/Irony/bin/%CONFIGURATION%/*.dll
  - 7z a irony.zip -r %APPVEYOR_BUILD_FOLDER%/Irony.Interpreter/bin/%CONFIGURATION%/*.dll
  - copy irony.zip irony-vs-v%APPVEYOR_BUILD_VERSION%.zip
  - copy irony.zip irony-vs-latest.zip
test:
  assemblies:
    only:
      - *.Tests.dll
artifacts:
  - path: irony-vs-v%APPVEYOR_BUILD_VERSION%.zip
    name: WithVersion
  - path: irony-vs-latest.zip
    name: Static
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
deploy:
