# https://www.appveyor.com/docs/appveyor-yml/

version: 1.1.0.{build}
branches:
  only:
    - master
skip_tags: true
image: Visual Studio 2017
platform:
  - Any CPU
configuration:
  - Release
build:
  parallel: true
  project: Irony-VS.sln
environment:
  EnableNuGetPackageRestore: true
before_build:
  nuget restore
after_build:
test:
  assemblies:
    only:
      - Irony.dll
      - Irony.Interpreter.dll
artifacts:
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
deploy:
